const prompt = {
    1: "A baseball field with the pitcher_s mound, home plate, and players in action",
    2: "A bridge with a sweeping view of the city skyline or natural landscape below",
    3: "A bustling city street with towering skyscrapers and busy pedestrians",
    4: "A bustling shopping mall parking lot with people coming and going and cars moving in all directions",
    5: "A charming rural town with a main street, old-fashioned shops, and a white picket fence",
    6: "A construction site with workers, equipment, and partially built structures",
    7: "A dark, eerie tunnel with cars speeding through and neon lights illuminating the way",
    8: "A deserted desert road with sand dunes and cacti as far as the eye can see",
    9: "A deserted highway stretching out into the horizon under a clear blue sky",
    10: "A farm field with rows of crops, a red barn, and a white farmhouse in the distance",
    11: "A football stadium with cheering fans and players running across the field",
    12: "A forest road with tall trees and dappled sunlight filtering through the leaves",
    13: "A golf course with rolling hills, sand traps, and water hazards",
    14: "A modern car dealership with shiny new vehicles on display",
    15: "A multi-level parking garage with cars moving up and down the ramps",
    16: "A nature reserve with hiking trails, wildlife, and beautiful scenery",
    17: "A picturesque urban park with trees, flowers, and a tranquil pond",
    18: "A racetrack with sleek cars speeding around the track and crowds of spectators",
    19: "A snow-covered road with frosted trees and a blanket of white snow on the ground",
    20: "A sprawling farm with fields of crops and animals grazing in the distance",
    21: "A suburban neighborhood street with well-manicured lawns and children playing in the yard.",
    22: "A sunny beach with palm trees, sand dunes, and waves crashing on the shore",
    23: "A tranquil lake or river with a reflection of the surrounding landscape in the water",
    24: "A vibrant downtown area with busy sidewalks, street performers, and storefronts",
    25: "A winding coastal road with stunning ocean views and rocky cliffs",
    26: "A winding countryside road with rolling hills and quaint farmhouses",
    27: "A winding mountain road with lush forests and breathtaking views",
    28: "airfield",
    29: "airplane cabin",
    30: "airport terminal",
    31: "alcove",
    32: "alley",
    33: "amphitheater",
    34: "amusement arcade",
    35: "amusement park",
    36: "An abandoned factory or warehouse with crumbling walls and broken windows",
    37: "An airport runway with planes taking off and landing in the background",
    38: "An amusement park with colorful rides, games, and people having fun",
    39: "apartment building",
    40: "aquarium",
    41: "aqueduct",
    42: "arcade",
    43: "arch",
    44: "archaelogical excavation",
    45: "archive",
    46: "army base",
    47: "art gallery",
    48: "art school",
    49: "art studio",
    50: "artists loft",
    51: "assembly line",
    52: "atrium",
    53: "attic",
    54: "auditorium",
    55: "auto factory",
    56: "auto showroom",
    57: "badlands",
    58: "bakery shop",
    59: "ball pit",
    60: "ballroom",
    61: "bamboo forest",
    62: "bank vault",
    63: "banquet hall",
    64: "bar",
    65: "barn",
    66: "barndoor",
    67: "baseball field",
    68: "baseball stadium",
    69: "basement",
    70: "bathroom",
    71: "beach house",
    72: "beach",
    73: "beauty salon",
    74: "bedchamber",
    75: "bedroom",
    76: "beer garden",
    77: "beer hall",
    78: "berth",
    79: "biology laboratory",
    80: "boardwalk",
    81: "boat deck",
    82: "boathouse",
    83: "bookstore",
    84: "botanical garden",
    85: "bowling alley",
    86: "boxing ring",
    87: "bridge",
    88: "broadleaf forest",
    89: "building facade",
    90: "bullring",
    91: "burial chamber",
    92: "bus interior",
    93: "bus station",
    94: "butchers shop",
    95: "butte",
    96: "cabin",
    97: "cafeteria",
    98: "campsite",
    99: "campus",
    100: "candy store",
    101: "canyon",
    102: "car interior",
    103: "carrousel",
    104: "castle",
    105: "catacomb",
    106: "cemetery",
    107: "chalet",
    108: "chemistry lab",
    109: "childs room",
    110: "church",
    111: "classroom",
    112: "clean room",
    113: "cliff",
    114: "closet",
    115: "clothing store",
    116: "coast",
    117: "cockpit",
    118: "coffee shop",
    119: "computer room",
    120: "concert arena",
    121: "conference center",
    122: "conference room",
    123: "construction site",
    124: "corn field",
    125: "corral",
    126: "corridor",
    127: "cottage",
    128: "courthouse",
    129: "courtyard",
    130: "creek",
    131: "crevasse",
    132: "crosswalk",
    133: "cultivated field",
    134: "dam",
    135: "delicatessen",
    136: "department store",
    137: "desert road",
    138: "desert",
    139: "diner",
    140: "dining hall",
    141: "dining room",
    142: "discotheque",
    143: "doorway",
    144: "dorm room",
    145: "downtown",
    146: "dressing room",
    147: "driveway",
    148: "drugstore",
    149: "elevator lobby",
    150: "elevator shaft",
    151: "elevator",
    152: "embassy",
    153: "engine room",
    154: "entrance hall",
    155: "escalator",
    156: "excavation",
    157: "exterior balcony",
    158: "exterior gazebo",
    159: "fabric store",
    160: "farm",
    161: "fastfood restaurant",
    162: "field road",
    163: "fire escape",
    164: "fire station",
    165: "fishpond",
    166: "food court",
    167: "football field",
    168: "football stadium",
    169: "forest path",
    170: "forest road",
    171: "formal garden",
    172: "fountain",
    173: "gas station",
    174: "gift shop",
    175: "glacier",
    176: "golf course",
    177: "grotto",
    178: "harbor",
    179: "hardware store",
    180: "hayfield",
    181: "heliport",
    182: "highway",
    183: "hockey arena",
    184: "home office",
    185: "home theater",
    186: "hospital room",
    187: "hospital",
    188: "hot spring",
    189: "hotel room",
    190: "hotel",
    191: "house",
    192: "hunting lodge",
    193: "ice cream parlor",
    194: "ice floe",
    195: "ice shelf",
    196: "iceberg",
    197: "igloo",
    198: "indoor basketball court ",
    199: "indoor bazaar",
    200: "indoor booth",
    201: "indoor bow window",
    202: "indoor flea market",
    203: "indoor florist shop",
    204: "indoor garage",
    205: "indoor general store",
    206: "indoor greenhouse",
    207: "indoor gymnasium",
    208: "indoor hangar",
    209: "indoor ice skating rink",
    210: "indoor market",
    211: "indoor parking garage",
    212: "indoor swimming pool",
    213: "industrial area",
    214: "inn",
    215: "interior balcony",
    216: "islet",
    217: "jacuzzi",
    218: "jail cell",
    219: "japanese garden",
    220: "jewelry shop",
    221: "junkyard",
    222: "kasbah",
    223: "kennel",
    224: "kindergarden classroom",
    225: "kitchen",
    226: "lagoon",
    227: "lake",
    228: "landfill",
    229: "landing deck",
    230: "laundromat",
    231: "lawn",
    232: "lecture room",
    233: "legislative chamber",
    234: "library",
    235: "lighthouse",
    236: "living room",
    237: "loading dock",
    238: "lobby",
    239: "lock chamber",
    240: "locker room",
    241: "mansion",
    242: "manufactured home",
    243: "marsh",
    244: "martial arts gym",
    245: "mausoleum",
    246: "medina",
    247: "mezzanine",
    248: "moat",
    249: "mosque",
    250: "motel",
    251: "mountain path",
    252: "mountain snowy",
    253: "mountain",
    254: "movie theater",
    255: "museum",
    256: "music studio",
    257: "natural canal",
    258: "natural history museum",
    259: "nursery",
    260: "nursing home",
    261: "oast house",
    262: "ocean",
    263: "office building",
    264: "office cubicles",
    265: "office",
    266: "oilrig",
    267: "operating room",
    268: "orchard",
    269: "orchestra pit",
    270: "outdoor athletic field",
    271: "outdoor bazaar",
    272: "outdoor garage",
    273: "outdoor general store",
    274: "outdoor greenhouse",
    275: "outdoor hangar",
    276: "outdoor ice skating rink",
    277: "outdoor market",
    278: "outdoor parking garage",
    279: "outdoor stage",
    280: "outdoor swimming pool",
    281: "pagoda",
    282: "palace",
    283: "pantry",
    284: "park",
    285: "parking lot",
    286: "pasture",
    287: "patio",
    288: "pavilion",
    289: "pet shop",
    290: "pharmacy",
    291: "phone booth",
    292: "physics laboratory",
    293: "picnic area",
    294: "pier",
    295: "pizzeria",
    296: "playground",
    297: "playroom",
    298: "plaza",
    299: "pond",
    300: "porch",
    301: "promenade",
    302: "pub",
    303: "racecourse",
    304: "raceway",
    305: "raft",
    306: "railroad track",
    307: "rainforest",
    308: "real ad 29",
    309: "real ad 30",
    310: "real ad 31",
    311: "real ad 32",
    312: "real ad 33",
    313: "reception",
    314: "recreation room",
    315: "repair shop",
    316: "residential neighborhood",
    317: "restaurant kitchen",
    318: "restaurant patio",
    319: "restaurant",
    320: "rice paddy",
    321: "river",
    322: "rock arch",
    323: "rodeo arena",
    324: "roof garden",
    325: "rope bridge",
    326: "ruin",
    327: "runway",
    328: "sandbox",
    329: "sauna",
    330: "schoolhouse",
    331: "science museum",
    332: "server room",
    333: "shed",
    334: "shoe shop",
    335: "shopfront",
    336: "shopping mall",
    337: "shower",
    338: "ski resort",
    339: "ski slope",
    340: "sky",
    341: "skyscraper",
    342: "slum",
    343: "snowfield",
    344: "soccer field",
    345: "soccer stadium",
    346: "stable",
    347: "stage",
    348: "staircase",
    349: "storage room",
    350: "street",
    351: "subway station",
    352: "supermarket",
    353: "sushi bar",
    354: "swamp",
    355: "swimming hole",
    356: "synagogue",
    357: "television room",
    358: "television studio",
    359: "temple",
    360: "throne room",
    361: "ticket booth",
    362: "topiary garden",
    363: "tower",
    364: "toyshop",
    365: "train interior",
    366: "train station",
    367: "tree farm",
    368: "tree house",
    369: "trench",
    370: "tundra",
    371: "underwater",
    372: "urban canal",
    373: "utility room",
    374: "valley",
    375: "vegetable garden",
    376: "veterinarians office",
    377: "viaduct",
    378: "village",
    379: "vineyard",
    380: "volcano",
    381: "volleyball court",
    382: "waiting room",
    383: "water park",
    384: "water tower",
    385: "waterfall",
    386: "watering hole",
    387: "wave",
    388: "wet bar",
    389: "wheat field",
    390: "wild field",
    391: "wind farm",
    392: "windmill",
    393: "yard",
    394: "zen garden",
}
// export { prompt };
